#!/usr/bin/perl
# 
# 
# 

use strict;

use lib "/opt/zimbra/zimbramon/lib";
use Zimbra::Util::Common;
use Zimbra::Mon::Logger;

my $platform=`/opt/zimbra/libexec/get_plat_tag.sh`;
chomp $platform;

my $MNTCMD;
my $DFCMD;
if ($platform eq "MACOSX") {
	$MNTCMD = "mount -t hfs";
	$DFCMD = "df -ml ";
} else {
	$MNTCMD = "mount -t ext3";
	$DFCMD = "df -ml ";
}

my $dt = `date "+%Y-%m-%d %H:%M:%S"`;
chomp $dt;

checkPid();
logQueue();
clearPid();

exit 0;

sub checkPid {
	if (-f "/opt/zimbra/log/zmqueuelog.pid") {
		my $P = `cat /opt/zimbra/log/zmqueuelog.pid`;
		chomp $P;
		if ($P ne "") {
      system("kill -0 $P 2> /dev/null");
      if ($? == 0) {
        print "$0 already running with pid $P\n";
        exit 0;
      }
		}
	}
	`echo $$ > "/opt/zimbra/log/zmqueuelog.pid"`;
}

sub clearPid {
	unlink ("/opt/zimbra/log/zmqueuelog.pid");
}

sub logQueue {
	my @status = ();
	open STATUS, "/opt/zimbra/postfix/sbin/postqueue -p |" or die "Can't get status: $!";
	@status = <STATUS>;
	close STATUS;
	my $kb = 0;
	my $msgs = 0;
	my $s = $status[$#status];
	if ($s =~ /^--/) {
		my @foo = split (' ', $s);
		$kb = $foo[1];
		$msgs = $foo[4];
	}
	Zimbra::Mon::Logger::Log( "info", "$dt, QUEUE: $kb $msgs" );
}
