#!/usr/bin/perl -w
# 
# 
# 

use strict;
use Getopt::Long;

my @interfaces = ();
open INTS, "/sbin/ifconfig | grep 'inet ' |";
foreach (<INTS>) {
  chomp;
  s/.*inet //;
  s/.addr: //;
  s/.(bcast|broadcast)[0-9:.\s]*//ig;
  s/.netmask\s/  Mask:/;
#  s/\s.*//;
#  s/[a-zA-Z:]//g;
  next if /^$/;
  push @interfaces, "addr:".$_;
}
close INTS;
my %seen;
if (scalar @interfaces) {
  foreach (@interfaces) {
    $seen{$_}++;
    print "$_\n" unless ($seen{$_} > 1);
  }
}

#/sbin/ifconfig | grep '	inet ' | sed -e 's/.*inet //' -e 's/\s.*//' -e 's/[a-zA-Z:]//g' | uniq 
#/sbin/ifconfig | sed -e '/^[ 	] *inet /!d' -e 's/.*inet //' -e 's/\s.*//' -e 's/[a-zA-Z:]//g' | uniq 
