#!/bin/bash
# 
# 
# 
umask 027
source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars \
	zimbra_home 

if [[ ! -L ${zimbra_home}/openldap && ! -d ${zimbra_home}/openldap ]]; then
	# No ldap - exit gracefully
	exit 0
fi

u=`id -un`
if [ $u != ${zimbra_user} ]; then
    echo "Error: must be run as ${zimbra_user} user"
    exit 1
fi

if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
	echo "USAGE: Exports LDAP databases"
	echo "Main database: zmslapcat <DIR>"
	echo "Config database: zmslapcat -c <DIR>"
	exit 1
fi

D=`date +%Y%m%d%H%M%S`
CONFIG=no
FILE=ldap.bak.${D}
NFILE=ldap.bak
if [ x$1 = "x-c" ]; then
	CONFIG=yes
	FILE=ldap-config.bak.${D}
	NFILE=ldap-config.bak
	DEST=$2
else
	DEST=$1
fi

mkdir -p $DEST
if [ x$CONFIG = "xyes" ]; then
	${zimbra_home}/openldap/sbin/slapcat -F ${zimbra_home}/data/ldap/config -n 0 -l ${DEST}/${FILE}
else
	${zimbra_home}/openldap/sbin/slapcat -F ${zimbra_home}/data/ldap/config -b "" -l ${DEST}/${FILE}
fi

cp -f ${DEST}/${FILE} ${DEST}/${NFILE}

