#!/usr/bin/perl
#/*
# * 
# */
#
# MacOS post installation script
#

use strict;
use warnings;

sub find_and_replace($$) {
    my ($file, $tokens) = @_;
    my $tmpfile = $file . '.tmp';
   
    open(FIN, "<$file") or die("Error: cannot open file $file\n");
    open(FOUT, ">$tmpfile") or die("Error: cannot open file $tmpfile\n");
   
    my $line;
    while($line = <FIN>){
        foreach my $key (keys(%$tokens)) {
            my $pos = index($line, $key);
            while ($pos >= 0) {
                substr($line, $pos, length($key), $tokens->{$key});
                $pos = index($line, $key);
            }
        }
        print FOUT $line;
    }
   
    close FIN;
    close FOUT;
   
    my (undef, undef, $mode) = stat($file);
    unlink $file;
    rename $tmpfile, $file;
    chmod $mode, $file;
}

my $app_root = $ARGV[1];
my $nwjs_helper_version = "50.0.2661.102";

system("mv \"$app_root/macos/Zimbra Desktop.app_noreloc\" \"$app_root/Zimbra Desktop.app\"");
system("mv \"$app_root/Zimbra Desktop.app/Contents/Versions/$nwjs_helper_version/nwjs Helper.framework\" \"$app_root/Zimbra Desktop.app/Contents/Versions/$nwjs_helper_version/nwjs Helper.app\"");
system("chown -R root:admin \"$app_root\"");

my $tokens = {
    '@INSTALL.APP.ROOT@' => $app_root,
    '@INSTALL.APP.TIMESTAMP@' => time()
};
find_and_replace("$app_root/Zimbra Desktop.app/Contents/MacOS/zdrun", $tokens);

# open zd app in finder
# system("open \"$app_root\"");

# launch zd
system("open \"$app_root/Zimbra Desktop.app\"");

